// Sample data for pet animals (replace with your own data)
const petAnimals = [
  {
      name: 'Cat',
      type: 'Mammal',
      diseases: ['Feline Leukemia', 'Feline Immunodeficiency Virus (FIV)', 'Upper Respiratory Infections'],
      medicines: ['Antibiotics', 'Antiviral medications'],
      veterinarians: ['Veterinarian C', 'Veterinarian D'],
      livingConditions: 'Quiet and cozy spaces',
      food: 'Balanced cat food',
      image: 'https://tse3.mm.bing.net/th?id=OIP.Bc0pBu6IEyF4vYo4j-ftggHaE8&pid=Api&P=0&h=180', 
  },
  {
      name: 'Dog',
      type: 'Mammal',
      diseases: ['Parvovirus', 'Rabies', 'Kennel Cough'],
      medicines: ['Antibiotics', 'Vaccines'],
      veterinarians: ['Veterinarian A', 'Veterinarian B'],
      livingConditions: 'Safe and spacious environment',
      food: 'High-quality dog food',
      image: 'http://static.businessinsider.com/image/5484d9d1eab8ea3017b17e29/image.jpg', 
  },
  {
    name: 'Fish',
    type: 'Aquatic',
    diseases: ['Ichthyophthirius (Ich)', 'Fin Rot', 'Swim Bladder Disorder'],
    medicines: ['Anti-parasitic medications'],
    veterinarians: ['Aquatic Veterinarian A', 'Aquatic Veterinarian B'],
    livingConditions: 'Properly filtered and aerated aquarium',
    food: 'Specialized fish flakes or pellets',
    image: 'https://tse4.mm.bing.net/th?id=OIP.4DdUGPI3pTi1eXgD-SiH7AHaE0&pid=Api&P=0&h=180',
},
{
  name: 'Hamster',
  type: 'Rodent',
  diseases: ['Wet Tail', 'Respiratory Infections'],
  medicines: ['Antibiotics'],
  veterinarians: ['Rodent Veterinarian A', 'Rodent Veterinarian B'],
  livingConditions: 'Comfortable and clean cage',
  food: 'Hamster pellets and fresh vegetables',
  image: 'https://tse1.mm.bing.net/th?id=OIP.kT-PDSBgtaZkPEPYtLQZZgHaHa&pid=Api&P=0&h=180',
},
{
  name: 'Parrot',
  type: 'Bird',
  diseases: ['Psittacosis', 'Aspergillosis', 'Papillomas'],
  medicines: ['Antibiotics', 'Antifungal medications'],
  veterinarians: ['Avian Veterinarian A', 'Avian Veterinarian B'],
  livingConditions: 'Spacious cage with toys',
  food: 'Nutritionally balanced bird pellets and fresh fruits',
  image: 'https://tse2.mm.bing.net/th?id=OIP.zneG2xOR5vDxXiX7jptb1AHaKG&pid=Api&P=0&h=180',
},
{
  name: 'Rabbit',
  type: 'Mammal',
  diseases: ['Rabbit Hemorrhagic Disease (RHD)', 'Hairball Obstruction', 'Pasteurellosis'],
  medicines: ['Vaccines', 'Hairball remedies'],
  veterinarians: ['Exotic Veterinarian A', 'Exotic Veterinarian B'],
  livingConditions: 'Spacious living area with hiding spots',
  food: 'Hay, fresh vegetables, and high-fiber pellets',
  image: 'https://tse2.mm.bing.net/th?id=OIP.DBY-P7MZ1Ybmtm6nVQjD0AHaEK&pid=Api&P=0&h=180',
},
{
  name: 'Snake',
  type: 'Reptile',
  diseases: ['Mites', 'Respiratory Infections', 'Scale Rot'],
  medicines: ['Anti-parasitic medications', 'Antibiotics'],
  veterinarians: ['Reptile Veterinarian A', 'Reptile Veterinarian B'],
  livingConditions: 'Properly sized enclosure with hiding spots',
  food: 'Appropriate-sized prey items',
  image: 'https://tse4.mm.bing.net/th?id=OIP.qR_tl91cftKfj_P9Y5GqgwHaEo&pid=Api&P=0&h=180',
},
{
  name: 'Turtle',
  type: 'Reptile',
  diseases: ['Shell Rot', 'Respiratory Infections', 'Metabolic Bone Disease'],
  medicines: ['Antibiotics', 'Vitamin and calcium supplements'],
  veterinarians: ['Reptile Veterinarian C', 'Reptile Veterinarian D'],
  livingConditions: 'Aquatic or semi-aquatic setup with basking area',
  food: 'Commercial turtle pellets and live or frozen prey',
  image: 'https://i.pinimg.com/originals/15/ed/d9/15edd9f6991b763e98f58acb67ced417.jpg',
},
{
  name: 'Bunny',
  type: 'Mammal',
  diseases: ['Gastrointestinal Stasis', 'Dental Issues', 'Myxomatosis'],
  medicines: ['Digestive medications', 'Dental procedures'],
  veterinarians: ['Exotic Veterinarian E', 'Exotic Veterinarian F'],
  livingConditions: 'Spacious hutch with hiding places',
  food: 'Hay, leafy greens, and high-fiber pellets',
  image: 'https://tse3.mm.bing.net/th?id=OIP.ls3hba3967TpdZii3OZNJgHaEK&pid=Api&P=0&h=180',
},
{
  name: 'Canary',
  type: 'Bird',
  diseases: ['Air Sac Mites', 'Avian Pox', 'Mycoplasma Infection'],
  medicines: ['Antiparasitic medications', 'Antibiotics'],
  veterinarians: ['Avian Veterinarian C', 'Avian Veterinarian D'],
  livingConditions: 'Well-ventilated cage with perches',
  food: 'Canary seed mix and fresh fruits',
  image: 'https://tse2.mm.bing.net/th?id=OIP.whTfHHBcR43_PAEkSMtCxQHaFS&pid=Api&P=0&h=180',
},
{
  name: 'Chinchilla',
  type: 'Rodent',
  diseases: ['Dental Malocclusion', 'Heat Stroke', 'Fur Slip'],
  medicines: ['Dental procedures', 'Cooling measures'],
  veterinarians: ['Rodent Veterinarian E', 'Rodent Veterinarian F'],
  livingConditions: 'Dust bath and multi-level cage',
  food: 'High-fiber chinchilla pellets and hay',
  image: 'https://tse2.mm.bing.net/th?id=OIP.pXMqyr-vPOrS_01SVWbiQwHaHa&pid=Api&P=0&h=180',
},
{
  name: 'Cockatiel',
  type: 'Bird',
  diseases: ['Psittacine Beak and Feather Disease (PBFD)', 'Respiratory Infections', 'Polyomavirus'],
  medicines: ['Antiviral medications', 'Antibiotics'],
  veterinarians: ['Avian Veterinarian E', 'Avian Veterinarian F'],
  livingConditions: 'Spacious cage with toys and perches',
  food: 'Nutritionally balanced cockatiel pellets and fresh vegetables',
  image: 'https://tse4.mm.bing.net/th?id=OIP.T0Xou4ycjVTQ7e5noGao5gHaE5&pid=Api&P=0&h=180',
},
{
  name: 'Dwarf Hamster',
  type: 'Rodent',
  diseases: ['Wet Tail', 'Diabetes', 'Respiratory Infections'],
  medicines: ['Antibiotics', 'Insulin for Diabetes'],
  veterinarians: ['Rodent Veterinarian G', 'Rodent Veterinarian H'],
  livingConditions: 'Small and secure cage with exercise wheel',
  food: 'Dwarf hamster pellets and fresh vegetables',
  image: 'https://tse4.mm.bing.net/th?id=OIP.W0NKWqt5zh1dmXKn7JUTUwHaE7&pid=Api&P=0&h=180',
},
{
  name: 'Fancy Goldfish',
  type: 'Aquatic',
  diseases: ['Swim Bladder Disorder', 'Ichthyophthirius (Ich)', 'Fin Rot'],
  medicines: ['Anti-parasitic medications'],
  veterinarians: ['Aquatic Veterinarian C', 'Aquatic Veterinarian D'],
  livingConditions: 'Properly sized aquarium with filtration',
  food: 'Specially formulated goldfish flakes and pellets',
  image: 'https://tse2.mm.bing.net/th?id=OIP.Q2pVH-KqR9KjENMkI_A3sgEADz&pid=Api&P=0&h=180',
},
{
  name: 'Gerbil',
  type: 'Rodent',
  diseases: ['Seizures', 'Tail Slipping', 'Respiratory Infections'],
  medicines: ['Anticonvulsants', 'Antibiotics'],
  veterinarians: ['Rodent Veterinarian I', 'Rodent Veterinarian J'],
  livingConditions: 'Cage with tunnels and climbing structures',
  food: 'Gerbil pellets and fresh vegetables',
  image: 'https://tse1.mm.bing.net/th?id=OIP.tauUglg1T18u814nm5MjKwHaHa&pid=Api&P=0&h=180',
},
{
  name: 'Hedgehog',
  type: 'Mammal',
  diseases: ['Wobbly Hedgehog Syndrome (WHS)', 'Mites', 'Respiratory Infections'],
  medicines: ['Supportive care for WHS', 'Antiparasitic medications'],
  veterinarians: ['Exotic Veterinarian G', 'Exotic Veterinarian H'],
  livingConditions: 'Enclosure with hiding spots and exercise wheel',
  food: 'High-quality hedgehog food and insects',
  image: 'https://tse4.mm.bing.net/th?id=OIP.ZF4TI73gz1uWqB3hJ40pFwHaEY&pid=Api&P=0&h=180',
},
{
  name: 'Iguana',
  type: 'Reptile',
  diseases: ['Metabolic Bone Disease (MBD)', 'Respiratory Infections', 'Parasitic Infections'],
  medicines: ['Calcium and vitamin supplements', 'Antibiotics'],
  veterinarians: ['Reptile Veterinarian E', 'Reptile Veterinarian F'],
  livingConditions: 'Large enclosure with basking and climbing areas',
  food: 'Leafy greens, vegetables, and occasional fruit',
  image: 'https://tse3.mm.bing.net/th?id=OIP.0VblqulJLSJhZMsSL2CPugHaEo&pid=Api&P=0&h=180',
},
{
  name: 'Lovebird',
  type: 'Bird',
  diseases: ['Psittacine Beak and Feather Disease (PBFD)', 'Respiratory Infections', 'Polyomavirus'],
  medicines: ['Antiviral medications', 'Antibiotics'],
  veterinarians: ['Avian Veterinarian G', 'Avian Veterinarian H'],
  livingConditions: 'Pair or group setting with toys and perches',
  food: 'Lovebird seed mix and fresh fruits',
  image: 'https://tse4.mm.bing.net/th?id=OIP.nHyCb5P_gyF25FTmDleiSQHaFj&pid=Api&P=0&h=180',
},
{
  name: 'Miniature Pig',
  type: 'Mammal',
  diseases: ['Obesity', 'Hoof Issues', 'Skin Conditions'],
  medicines: ['Weight management', 'Hoof care'],
  veterinarians: ['Exotic Veterinarian I', 'Exotic Veterinarian J'],
  livingConditions: 'Outdoor pen with shelter and mud wallow',
  food: 'Balanced pig pellets and fresh vegetables',
  image: 'https://s.abcnews.com/images/Lifestyle/AP_micro_pigs_2_sr_140319_1x1_1600.jpg',
},
{
  name: 'Netherland Dwarf Rabbit',
  type: 'Mammal',
  diseases: ['Gastrointestinal Stasis', 'Dental Issues', 'Myxomatosis'],
  medicines: ['Digestive medications', 'Dental procedures'],
  veterinarians: ['Exotic Veterinarian K', 'Exotic Veterinarian L'],
  livingConditions: 'Spacious hutch with hiding spots',
  food: 'Hay, leafy greens, and high-fiber pellets',
  image: 'https://tse1.mm.bing.net/th?id=OIP.KiRvvmuTtIknKp1DwAYSOwHaHc&pid=Api&P=0&h=180',
},
{
  name: 'Oscar Fish',
  type: 'Aquatic',
  diseases: ['Hole-in-the-Head Disease', 'Ichthyophthirius (Ich)', 'Fin Rot'],
  medicines: ['Anti-parasitic medications'],
  veterinarians: ['Aquatic Veterinarian E', 'Aquatic Veterinarian F'],
  livingConditions: 'Large tank with hiding places and proper filtration',
  food: 'Specially formulated cichlid pellets and live or frozen prey',
  image: 'https://tse4.mm.bing.net/th?id=OIP.gUvuNaIK6b231bu55YJQvAHaFj&pid=Api&P=0&h=180',
},
{
  name: 'Pomeranian',
  type: 'Mammal',
  diseases: ['Luxating Patella', 'Dental Issues', 'Skin Allergies'],
  medicines: ['Joint supplements', 'Dental care products'],
  veterinarians: ['Canine Veterinarian A', 'Canine Veterinarian B'],
  livingConditions: 'Indoor living with regular exercise',
  food: 'High-quality dog food and occasional treats',
  image: 'https://tse1.mm.bing.net/th?id=OIP.rhJ3ATG6kZ6lCE6BSUzLsQHaFc&pid=Api&P=0&h=180',
},
{
  name: 'Quaker Parrot',
  type: 'Bird',
  diseases: ['Aspergillosis', 'Psittacosis', 'Polyomavirus'],
  medicines: ['Antifungal medications', 'Antibiotics'],
  veterinarians: ['Avian Veterinarian I', 'Avian Veterinarian J'],
  livingConditions: 'Spacious cage with toys and perches',
  food: 'Nutritionally balanced bird pellets and fresh vegetables',
  image: 'https://facts.net/wp-content/uploads/2020/10/Quaker-Parrot.jpg',
},
{
  name: 'Russian Tortoise',
  type: 'Reptile',
  diseases: ['Respiratory Infections', 'Metabolic Bone Disease (MBD)', 'Parasitic Infections'],
  medicines: ['Antibiotics', 'Calcium and vitamin supplements'],
  veterinarians: ['Reptile Veterinarian G', 'Reptile Veterinarian H'],
  livingConditions: 'Enclosure with basking area and hiding spots',
  food: 'Leafy greens, vegetables',
  image: 'https://tse4.mm.bing.net/th?id=OIP.Nr1lkF-x7ejopeB6z2_g0QHaFj&pid=Api&P=0&h=180',
},

{
  name: 'Pig',
  type: 'Mammal',
  diseases: ['Swine Flu', 'Foot-and-Mouth Disease', 'Porcine Reproductive and Respiratory Syndrome (PRRS)'],
  medicines: ['Antibiotics', 'Vaccines'],
  veterinarians: ['Veterinarian E', 'Veterinarian F'],
  livingConditions: 'Sturdy and well-ventilated pen',
  food: 'Balanced pig feed',
  image: 'https://tse3.mm.bing.net/th?id=OIP.fwcuGYw3Z-XPYntU5qf_LQHaFG&pid=Api&P=0&h=180',
},
{
  name: 'Horse',
  type: 'Mammal',
  diseases: ['Equine Influenza', 'Colic', 'Strangles'],
  medicines: ['Anti-inflammatory drugs', 'Vaccines'],
  veterinarians: ['Veterinarian G', 'Veterinarian H'],
  livingConditions: 'Spacious and clean stable',
  food: 'Quality horse hay and grains',
  image: 'https://tse1.mm.bing.net/th?id=OIP.4g2K8JaV8HK1Kz865lrYLQHaE7&pid=Api&P=0&h=180', 
},
{
  name: 'Camel',
  type: 'Mammal',
  diseases: ['Camel Pox', 'MERS (Middle East Respiratory Syndrome)', 'Foot Rot'],
  medicines: ['Antibiotics', 'Vaccines'],
  veterinarians: ['Veterinarian I', 'Veterinarian J'],
  livingConditions: 'Desert environment with shade',
  food: 'Dry grass and grains',
  image: 'https://tse4.explicit.bing.net/th?id=OIP.anaUmSB690bF9WcxHuyQ_wHaFj&pid=Api&P=0&h=180', 
},
{
  name: 'Kingfisher',
  type: 'Bird',
  diseases: ['Avian Influenza', 'Aspergillosis', 'Botulism'],
  medicines: ['Antibiotics', 'Antifungal medications'],
  veterinarians: ['Avian Veterinarian C', 'Avian Veterinarian D'],
  livingConditions: 'Natural pond or water body',
  food: 'Small fish and insects',
  image: 'https://tse2.mm.bing.net/th?id=OIP.Uikv2dQSN1c6wAuO3JAQGAHaFZ&pid=Api&P=0&h=180', 
},
{
  name: 'Tiger',
  type: 'Mammal',
  diseases: ['Feline Leukemia', 'Canine Distemper', 'Feline Infectious Peritonitis (FIP)'],
  medicines: ['Antibiotics', 'Vaccines'],
  veterinarians: ['Wildlife Veterinarian A', 'Wildlife Veterinarian B'],
  livingConditions: 'Large and natural enclosure',
  food: 'Meat-based diet',
  image: 'https://tse2.mm.bing.net/th?id=OIP.zb2bMkSw2aP62F8liqmASQHaE8&pid=Api&P=0&h=180',
},
{
  name: 'Baby Shark',
  type: 'Fish',
  diseases: ['Ichthyophthirius (Ich)', 'Columnaris Disease', 'Fish Tuberculosis'],
  medicines: ['Anti-parasitic medications', 'Antibiotics'],
  veterinarians: ['Aquatic Veterinarian C', 'Aquatic Veterinarian D'],
  livingConditions: 'Large aquarium with hiding spots',
  food: 'Small fish and specialized shark pellets',
  image: 'https://tse3.mm.bing.net/th?id=OIP.VaR28wM1_tFhNoY6eqoQfAHaE8&pid=Api&P=0&h=180', 
},
{
  name: 'Cow',
  type: 'Mammal',
  diseases: ['Bovine Respiratory Disease (BRD)', 'Mastitis', 'Hoof Rot'],
  medicines: ['Antibiotics', 'Vaccines'],
  veterinarians: ['Veterinarian K', 'Veterinarian L'],
  livingConditions: 'Spacious and clean barn',
  food: 'Quality hay and grains',
  image: 'https://tse2.mm.bing.net/th?id=OIP.c6LNuQclyKg2Ar3ffeHx9gHaFj&pid=Api&P=0&h=180',
},
{
  name: 'Goat',
  type: 'Mammal',
  diseases: ['Caprine Arthritis Encephalitis (CAE)', 'Caseous Lymphadenitis (CL)', 'Foot Rot'],
  medicines: ['Antibiotics', 'Vaccines'],
  veterinarians: ['Veterinarian M', 'Veterinarian N'],
  livingConditions: 'Sturdy and well-ventilated pen',
  food: 'Balanced goat feed',
  image: 'https://images.pexels.com/photos/1011630/pexels-photo-1011630.jpeg?cs=srgb&dl=animal-white-young-1011630.jpg&fm=jpg',
},
{
  name: 'Hens',
  type: 'Bird',
  diseases: ['Avian Influenza', 'Coccidiosis', 'Egg-Laying Issues'],
  medicines: ['Antibiotics', 'Vitamins'],
  veterinarians: ['Poultry Veterinarian A', 'Poultry Veterinarian B'],
  livingConditions: 'Coop with nesting boxes',
  food: 'Poultry feed and grains',
  image: 'https://tse2.mm.bing.net/th?id=OIP.JZ92nWrK28FnazBp82XgOAHaFI&pid=Api&P=0&h=180',
},
{
  name: 'Sheep',
  type: 'Mammal',
  diseases: ['Ovine Progressive Pneumonia (OPP)', 'Foot Rot', 'Internal Parasites'],
  medicines: ['Antibiotics', 'Anthelmintics'],
  veterinarians: ['Veterinarian O', 'Veterinarian P'],
  livingConditions: 'Sturdy and well-ventilated pen',
  food: 'Quality hay and grains',
  image: 'https://tse4.mm.bing.net/th?id=OIP.kQMwgCq5WAaeEa21uKR-ZwHaE8&pid=Api&P=0&h=180',
},
{
  name: 'Golden Retriever',
  type: 'Mammal',
  diseases: ['Hip Dysplasia', 'Cancer', 'Heart Disease'],
  medicines: ['Pain medications', 'Chemotherapy'],
  veterinarians: ['Veterinarian Q', 'Veterinarian R'],
  livingConditions: 'Safe and spacious environment',
  food: 'High-quality dog food',
  image: 'https://tse1.mm.bing.net/th?id=OIP.Inj7LYXYqqhq82d8uqZ6_wHaHL&pid=Api&P=0&h=180',
},
{
  name: 'Deer',
  type: 'Mammal',
  diseases: ['Chronic Wasting Disease (CWD)', 'Lyme Disease', 'Parasitic Infections'],
  medicines: ['Antibiotics', 'Anthelmintics'],
  veterinarians: ['Wildlife Veterinarian C', 'Wildlife Veterinarian D'],
  livingConditions: 'Natural woodland habitat',
  food: 'Natural vegetation',
  image: 'https://tse2.mm.bing.net/th?id=OIP.1BSoI4ZDusTfKoHl_ZhE3AHaEo&pid=Api&P=0&h=180',
},
{
  name: 'Bull',
  type: 'Mammal',
  diseases: ['Bovine Respiratory Disease (BRD)', 'Hoof Rot', 'Trichomoniasis'],
  medicines: ['Antibiotics', 'Vaccines'],
  veterinarians: ['Veterinarian S', 'Veterinarian T'],
  livingConditions: 'Spacious and clean barn',
  food: 'Quality hay and grains',
  image: 'https://media.istockphoto.com/photos/bull-picture-id915883018?k=6&m=915883018&s=612x612&w=0&h=jmSlYqzvFihcYhuVQTMFoOsFIcRX1mP3VTQ3-n3MEUs=',
},
{
  name: 'Ox',
  type: 'Mammal',
  diseases: ['Hoof Rot', 'Internal Parasites', 'Bloat'],
  medicines: ['Antibiotics', 'Anthelmintics'],
  veterinarians: ['Veterinarian U', 'Veterinarian V'],
  livingConditions: 'Sturdy and well-ventilated pen',
  food: 'Quality hay and grains',
  image: 'https://cdn.britannica.com/13/136113-050-F7237AC8/Oxen.jpg',
},
{
  name: 'Pigeon',
  type: 'Bird',
  diseases: ['Pigeon Paramyxovirus (PPMV)', 'Canker', 'Respiratory Infections'],
  medicines: ['Antibiotics', 'Antifungal medications'],
  veterinarians: ['Avian Veterinarian E', 'Avian Veterinarian F'],
  livingConditions: 'Coop with nesting boxes',
  food: 'Pigeon feed and grains',
  image: 'https://voice.gardenbird.co.uk/wp-content/uploads/2017/07/Wood-pigeon-Calumba-palumbus.jpg',
},
  // Add more animals with similar structure
];

const animalList = document.getElementById('animalList');
const searchInput = document.getElementById('searchInput');

// Function to display pet animals
function displayPetAnimals(animals) {
  animalList.innerHTML = '';

  animals.forEach(animal => {
      const card = document.createElement('div');
      card.classList.add('card');
      card.innerHTML = `
          <h2>${animal.name}</h2>
          <img src="${animal.image}" alt="${animal.name}">
          <p>Type: ${animal.type}</p>
          <p>Diseases: ${animal.diseases.join(', ')}</p>
          <p>Medicines: ${animal.medicines.join(', ')}</p>
          <p>Veterinarians: ${animal.veterinarians.join(', ')}</p>
          <p>Living Conditions: ${animal.livingConditions}</p>
          <p>Food: ${animal.food}</p>
      `;
      animalList.appendChild(card);
  });
}

// Initial display
displayPetAnimals(petAnimals);

// Search functionality
searchInput.addEventListener('input', () => {
  const searchTerm = searchInput.value.toLowerCase();
  const filteredAnimals = petAnimals.filter(animal =>
      animal.name.toLowerCase().includes(searchTerm) ||
      animal.type.toLowerCase().includes(searchTerm)
  );
  displayPetAnimals(filteredAnimals);
});
